Fix/#5ccwbj
dannylekim/billsnapFront pull request #40
Opened 2020-06-21 17:34 UTC by alphakennyn

2020-06-21 17:34 UTC, dannylekim commented
Task linked: [CU-5ccwbj Login/Register page v2](https://app.clickup.com/t/5ccwbj)

2020-06-21 23:03 UTC, Kevinjhlin approved these changes

2020-06-28 16:29 UTC, briankimlim submitted a review, later dismissed
The Login form should be the default form open instead of Register

2020-06-28 16:32 UTC, briankimlim requested changes
On register form: 'Submit' button should be changed for "Sign Up" or "Sign Up for BillSnap"

Personally I think Login Form should be the one open by default. I expect this from other sites, so having the Register form open by default, but seeing "Submit" button, it's not clear I'm seeing a Register form until I see all the way at the bottom that there's a Login switch button

2020-06-28 18:27 UTC, briankimlim approved these changes

2020-06-28 18:30 UTC, merged