Feat/#8rdhyr #9ujbzp
dannylekim/billsnapFront pull request #49
Opened 2020-07-20 22:43 UTC by asianswagstorm

2020-07-20 22:43 UTC, dannylekim commented
Task linked: [CU-9ujbzp Bill display update 2](https://app.clickup.com/t/9ujbzp)

2020-07-20 22:43 UTC, dannylekim commented
Task linked: [CU-8rdhyr Home Dashboard v2](https://app.clickup.com/t/8rdhyr)

2020-07-21 01:52 UTC, alphakennyn requested changes

2020-07-21 01:52 UTC, alphakennyn commented on src/views/BillDisplay/BillDisplay.jsx
> +                onClick: () => this.updateBills("A to Z")
can you use some `id` to determine sort type?

2020-07-21 01:52 UTC, alphakennyn commented on src/utils/requests/BillRequests.js
> +export const getBill = async (query_params) => {
use default params, so you don't need to define param

```suggestion
export const getBill = async (query_params = '') => {
```

2020-07-21 01:52 UTC, alphakennyn commented on src/views/BillDisplay/BillDisplay.jsx
> +        <div className="advanced__filter__selection">
WIth just a quick glance, you can tell this code is really hectic to read. Why don't you separate this into another component

2020-07-21 01:52 UTC, alphakennyn commented on src/views/BillDisplay/BillDisplay.jsx
> +        <div className="advanced__filter__selection">
Ill leave the naming up to you

2020-07-21 20:42 UTC, dannylekim commented
![image](https://user-images.githubusercontent.com/26320256/88104894-1e668680-cb71-11ea-9d6c-694e56ffd4bf.png)

2020-07-22 03:18 UTC, alphakennyn requested changes

2020-07-22 03:18 UTC, alphakennyn commented on src/components/BillFilter/BillFilter.jsx
> +const BillFilter = ({dateFilters,filter,billStatusFilter, handleDateSelection,updateBills,setState}) => {
very nice! Can you please format your code?

2020-07-22 03:18 UTC, alphakennyn commented on src/components/BillFilter/BillFilter.jsx
> +    {  (filter.dateOpened === true  || filter.statusOpened === true || filter.categoryOpened === true) &&
can you assign this condition to a some variable? Cleaner that way

2020-07-26 15:57 UTC, alphakennyn approved these changes

2020-07-26 15:59 UTC, merged