Feat/#8rdhyr #5cbhx2
dannylekim/billsnapFront pull request #50
Opened 2020-07-21 04:12 UTC by Kevinjhlin

Please review my work, I feel like I might not be doing it right

2020-07-21 04:12 UTC, dannylekim commented
Task linked: [CU-5cbhx2 Logout](https://app.clickup.com/t/5cbhx2)

2020-07-21 04:12 UTC, dannylekim commented
Task linked: [CU-8rdhyr Home Dashboard v2](https://app.clickup.com/t/8rdhyr)

2020-07-21 22:45 UTC, asianswagstorm approved these changes
I fixed the useInfo redux and updated some previous tests by adding provider.

2020-07-22 03:09 UTC, alphakennyn requested changes

2020-07-22 03:09 UTC, alphakennyn commented on src/views/LoginForm/LoginForm.jsx
> +        console.log(userProfile);
please remove

2020-07-22 03:09 UTC, alphakennyn commented on src/components/Sidebar/Sidebar.jsx
> +        localStorage.clear();
normally we shouldn't clear all of the client browser's local-storage. Just get rid of our token `billsnap-token`

2020-07-22 04:44 UTC, Kevinjhlin commented on src/components/Sidebar/Sidebar.jsx
> +        localStorage.removeItem("billSnap_token");
@alphakennyn

2020-07-22 04:45 UTC, Kevinjhlin commented on src/views/LoginForm/LoginForm.jsx
> +        this.props.setUser(userProfile);
@alphakennyn Removed console.log

2020-07-22 05:20 UTC, dannylekim commented
@alphakennyn  @Kevinjhlin  

If there's no way for us to up that code coverage on the added code, then lmk and I can force merge. But ideally we should be able to hit the code that's been added rather than 80%

2020-07-24 01:31 UTC, alphakennyn approved these changes

2020-07-24 18:09 UTC, merged