Feat/#8ug661 #b0n1zj
dannylekim/billsnapFront pull request #58
Opened 2020-08-14 15:25 UTC by dannylekim

![image](https://user-images.githubusercontent.com/26320256/90265626-dc073100-de20-11ea-8f1d-07aff2a50faa.png)

2020-08-14 15:25 UTC, dannylekim commented
Task linked: [CU-8ug661 View pending Bills](https://app.clickup.com/t/8ug661)

2020-08-14 15:25 UTC, dannylekim commented
Task linked: [CU-b0n1zj Create presentational component](https://app.clickup.com/t/b0n1zj)

2020-08-16 15:48 UTC, alphakennyn requested changes

2020-08-16 15:48 UTC, alphakennyn commented on src/components/PendingBillCard/PendingBillCard.jsx
> +            {bill.responsible && (
```suggestion
            {!!bill.responsible && (
```

2020-08-16 15:51 UTC, alphakennyn approved these changes

2020-08-16 15:56 UTC, merged